apiVersion: apps/v1
kind: Deployment
metadata:
  name: ongs-deployment
  labels:
    app: ongs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ongs
  template:
    metadata:
      labels:
        app: ongs
    spec:
      containers:
      - name: ongs
        image: fephs/ongs:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: ongs-service
spec:
  selector:
    app: ongs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080