apiVersion: apps/v1
kind: Deployment
metadata:
  name: adotantes-deployment
  labels:
    app: adotantes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adotantes
  template:
    metadata:
      labels:
        app: adotantes
    spec:
      containers:
      - name: adotantes
        image: fephs/adotantes:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: SPRING_CONFIG_IMPORT
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom: 
            configMapKeyRef:
              name: petbytes-configmap
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: adotantes-service
spec:
  selector:
    app: adotantes
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081