version: "3.8"

services: 

  configserver:
    image: fephs/configserver:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - petbytes

  ongs:
    image: fephs/ongs:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - petbytes
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090

  adotantes:
    image: fephs/adotantes:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - petbytes
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090

networks:
  petbytes: